# Generated by Django 4.0.2 on 2022-04-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_category_whatchlist_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_reverse', to='auctions.Category'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
