# Generated by Django 4.0.2 on 2022-04-18 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listing_category_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='owner_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_reverse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='winner_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner_reverse', to=settings.AUTH_USER_MODEL),
        ),
    ]
