# Generated by Django 4.0.2 on 2022-04-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listing_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='listing_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='picture_url',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
