# Generated by Django 4.0.2 on 2022-04-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listing_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='picture_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
