# Generated by Django 4.0.2 on 2022-04-25 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_listing_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
