# Generated by Django 4.0.2 on 2022-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_listing_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
