# Generated by Django 4.0.2 on 2022-04-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auction_listing_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='current_price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
