# Generated by Django 4.0.2 on 2022-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_listing_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='picture',
            field=models.ImageField(blank=True, default='/media/images/No_Image_Available.jpg', upload_to='images'),
        ),
    ]
