# Generated by Django 4.0.2 on 2022-05-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_listing_id_comments_listingid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing_id',
            new_name='listingid',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='whatchlist',
            old_name='listing_id',
            new_name='listingid',
        ),
        migrations.RenameField(
            model_name='whatchlist',
            old_name='user_id',
            new_name='userid',
        ),
    ]
