# Generated by Django 4.0.2 on 2022-05-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_whatchlist_on_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatchlist',
            name='inwatchlist',
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name=''),
        ),
    ]
