# Generated by Django 4.0.2 on 2022-05-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_whatchlist_inwatchlist_alter_bids_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='owner_id',
            new_name='ownerid',
        ),
        migrations.RenameField(
            model_name='auction_listing',
            old_name='winner_id',
            new_name='winnerid',
        ),
    ]
