# Generated by Django 4.0.2 on 2022-07-11 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_owner_id_auction_listing_ownerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatchlist',
            name='userid',
        ),
        migrations.AddField(
            model_name='whatchlist',
            name='userid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
